Repository SOPT-all/35-COLLABORATION-iOS-KAKAOWEBTOON, pull requests merged in 2024-11, with the labels that each got.

#2 [Setting] #1 - 프로젝트 폴더링 세팅
  .gitignore
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS.xcodeproj/project.pbxproj
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/configuration/.gitkeep
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS.xcodeproj/project.xcworkspace/xcuserdata/jiwon.xcuserdatad/UserInterfaceState.xcuserstate
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS.xcodeproj/xcuserdata/jiwon.xcuserdatad/xcschemes/xcschememanagement.plist
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Application/AppDelegate.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Application/SceneDelegate.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Base.lproj/LaunchScreen.storyboard
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Base.lproj/Main.storyboard
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Extension/.gitkeep
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Literals/Literal/.gitkeep
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Literals/String/.gitkeep
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Protocols/.gitkeep
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Resources/Assets.xcassets/Contents.json
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Resources/Info.plist
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Network/Base/.gitkeep
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Network/DataModel/.gitkeep
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Network/Service/.gitkeep
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Common/UIComponents/.gitkeep
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Episode/Cell/.gitkeep
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Episode/Model/.gitkeep
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Episode/View/.gitkeep
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Episode/ViewController/.gitkeep
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Home/Cell/.gitkeep
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Home/Model/.gitkeep
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Home/View/.gitkeep
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Home/ViewController/.gitkeep
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Search/Cell/.gitkeep
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Search/Model/.gitkeep
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Search/View/.gitkeep
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Search/ViewController/.gitkeep
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Storage/Cell/.gitkeep
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Storage/Model/.gitkeep
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Storage/View/.gitkeep
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Storage/ViewController/.gitkeep
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/ViewController.swift
Labels: 🍙Setting, 지원🍒

#6 [Add] #5 FontLiteral 추가
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS.xcodeproj/project.pbxproj
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Extension/UILabel+.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Literals/Literal/FontLiteral.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Resources/Assets.xcassets/AppColor/primaryBlue.colorset/Contents.json
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Resources/Assets.xcassets/AppColor/primaryRed.colorset/Contents.json
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Resources/Assets.xcassets/AppColor/primaryWhite.colorset/Contents.json
Labels: 승원🍋, 🪐Chore

#8 [Add] #7 Extensions, TabBarController 추가
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS.xcodeproj/project.pbxproj
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Application/SceneDelegate.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Base.lproj/Main.storyboard
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Extension/UIFont+.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Extension/UIStackView+.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Extension/UIView+.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Literals/Literal/FontLiteral.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Protocols/ReuseIdentifiable.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Resources/Info.plist
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Home/ViewController/HomeViewController.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Storage/ViewController/StorageViewController.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/TabBar/ViewControllers/KWTabBarController.swift
Labels: 🍙Setting, 승원🍋, 🪐Chore

#10 [Setting] #9 - 라이브러리 최신 버전 다운로드
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS.xcodeproj/project.pbxproj
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS.xcodeproj/xcuserdata/jiwon.xcuserdatad/xcschemes/xcschememanagement.plist
Labels: 🍙Setting, 지원🍒

#13 [Feat] #12 NavigationBar 기본 구축
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS.xcodeproj/project.pbxproj
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Extension/UIBarButtonItem+.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Extension/UINavigationBar+.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Storage/View/StorageView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Storage/ViewController/StorageViewController.swift
Labels: ☃️Feat, 승원🍋

#22 [Feat] #11 보관함 재사용 셀 구현
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS.xcodeproj/project.pbxproj
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS.xcodeproj/xcuserdata/won.xcuserdatad/xcschemes/xcschememanagement.plist
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Protocols/ReuseIdentifiable.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Common/Cells/WebToonBoxCell.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Common/Views/FreeTagView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Common/Views/HashTagView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Storage/View/StorageHeaderRadioButton.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Storage/View/StorageHeaderView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Storage/View/StorageView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Storage/ViewController/StorageViewController.swift
Labels: ☃️Feat, 승원🍋

#18 [Feat] #17 - 에피소드 셀 UI 생성 및 진행도 함수 구현
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS.xcodeproj/project.pbxproj
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS.xcodeproj/xcuserdata/jiwon.xcuserdatad/xcschemes/xcschememanagement.plist
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Episode/Cell/EpisodeCell.swift
Labels: ☃️Feat, 지원🍒, 🎨Style

#24 [Feat] #23 - 보관함 헤더 UI 구현
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS.xcodeproj/project.pbxproj
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Common/Cells/WebToonBoxCell.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Storage/View/CategorySelectorView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Storage/View/CategoryTabView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Storage/View/StorageHeaderView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Storage/View/StorageView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Storage/View/ToolTabView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Storage/ViewController/StorageViewController.swift
Labels: ☃️Feat, 승원🍋, 🎨Style

#28 [Feat] #26 - 검색 네비게이션 바 UI 구현
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS.xcodeproj/project.pbxproj
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Extension/UINavigationBar+.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Extension/UITextField+.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Search/View/SearchView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Search/ViewController/SearchViewController.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Search/ViewController/TempViewController.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/TabBar/ViewControllers/KWTabBarController.swift
Labels: ☃️Feat, 승원🍋, 🎨Style

#34 [Feat] #30 - FilterTabView 구현
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS.xcodeproj/project.pbxproj
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS.xcodeproj/xcuserdata/jiwon.xcuserdatad/xcschemes/xcschememanagement.plist
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS.xcodeproj/xcuserdata/won.xcuserdatad/xcschemes/xcschememanagement.plist
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Search/View/FilterTabView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Search/View/SearchView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Search/ViewController/SearchViewController.swift
Labels: ☃️Feat, 승원🍋, 🎨Style

#37 [Chore] #32 - 홈뷰 웹툰리스트 레이아웃 수정
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Home/Cell/AllToonsSectionCell.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Home/View/HomeView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Home/ViewController/HomeViewController.swift
Labels: 현수🍉, 🪐Chore, 🎨Style

#38 [Feat] #35 - 보관함뷰 CollectionView
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS.xcodeproj/project.pbxproj
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Extension/UINavigationBar+.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Search/View/FilterTabView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Search/View/RecommandHeaderView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Search/View/ResultHeaderView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Search/View/SearchView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Search/ViewController/SearchViewController.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Search/ViewController/TempViewController.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Storage/View/CategorySelectorView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Storage/View/CategoryTabView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Storage/View/StorageView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Storage/View/ToolTabView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Storage/ViewController/StorageViewController.swift
Labels: ☃️Feat, 승원🍋, 🎨Style

#40 [Feat] #36 - 검색 플로우 구현
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Search/View/SearchView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Search/ViewController/SearchViewController.swift
Labels: ☃️Feat, 승원🍋

#39 [Feat] #27 - 에피소드 탭바 UI 구현 및 헤더 뷰 자잘한 수정사항 적용
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS.xcodeproj/project.pbxproj
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Episode/View/EpisodeHeaderView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Episode/View/EpisodeTabBarView.swift
Labels: ☃️Feat, 지원🍒, 🎨Style

#43 [Setting] #42 - 네트워크 통신 기본 세팅
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS.xcodeproj/project.pbxproj
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Network/Base/BaseService.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Network/Base/BaseTargetType.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Network/Base/ErrorResponseDTO.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Network/Base/MoyaPlugin.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Network/Base/NetworkResult.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Network/Base/NetworkServce.swift
Labels: 🍙Setting, 지원🍒

#46 [Setting] #45 - TargetType, DTO 파일 추가
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS.xcodeproj/project.pbxproj
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Resources/Info.plist
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Network/Base/BaseTargetType.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Network/Base/EpisodeTargetType.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Network/Base/WebtoonTargetType.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Network/DataModel/GetDailyWebtoonResponseDTO.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Network/DataModel/GetEpisodeDetailResponseDTO.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Network/DataModel/GetEpisodeHeaderRepsponseDTO.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Network/DataModel/GetRecentWebtoonResponseDTO.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Network/DataModel/GetWebtoonSearchResponseDTO.swift
Labels: 🍙Setting, 지원🍒

#49 [Network] #48 - Service 파일 생성
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS.xcodeproj/project.pbxproj
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Network/Service/EpisodeService.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Network/Service/WebtoonService.swift
Labels: 🧤Network, 🍙Setting, 지원🍒

#50 [Feat] #47 - 보관함뷰 API 연결
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS.xcodeproj/project.pbxproj
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Network/DataModel/GetRecentWebtoonResponseDTO.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Network/DataModel/GetWebtoonSearchResponseDTO.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Network/Service/WebtoonService.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Common/Cells/WebToonBoxCell.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Common/Enums/FreeTagViewType.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Common/Views/FreeTagView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Search/ViewController/SearchViewController.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Storage/ViewController/StorageViewController.swift
Labels: 🧤Network, ☃️Feat, 승원🍋

#52 [Feat] #33 -웹툰 카테고리 섹션 UI
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS.xcodeproj/project.pbxproj
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Resources/Assets.xcassets/AppImage/main/img_under_line.imageset/Contents.json
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Resources/Assets.xcassets/AppImage/main/img_under_line.imageset/yellowUnderLine.svg
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Home/Cell/ToonCategorySectionCell.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Home/Cell/adSectionCell.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Home/Model/ToonGenreApp.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Home/View/AllToonsSectionFooterView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Home/View/AllToonsSectionHeaderView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Home/View/HomeView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Home/View/ToonCategoryHeaderView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Home/ViewController/HomeViewController.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Storage/ViewController/StorageViewController.swift
Labels: 현수🍉, ☃️Feat, 🎨Style

#55 [Feat] #51 - 검색뷰 API 연결
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS.xcodeproj/project.pbxproj
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Resources/Assets.xcassets/AppImage/search/ic_nil.imageset/Contents.json
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Resources/Assets.xcassets/AppImage/search/ic_nil.imageset/nilImage.svg
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Network/DataModel/GetWebtoonSearchResponseDTO.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Network/Service/WebtoonService.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Common/Cells/WebToonBoxCell.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Search/Model/RecommandWebtoon.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Search/View/ResultHeaderView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Search/ViewController/SearchViewController.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Storage/ViewController/StorageViewController.swift
Labels: 🧤Network, ☃️Feat, 승원🍋

#57 [Feat] #56 - 홈뷰, 보관함뷰 -> 검색뷰 연결
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS.xcodeproj/project.pbxproj
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Home/ViewController/HomeViewController.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Search/ViewController/TempViewController.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Storage/ViewController/StorageViewController.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/TabBar/ViewControllers/KWTabBarController.swift
Labels: ☃️Feat, 승원🍋

#58 [Feat] #53 - 홈뷰 API 연결
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS.xcodeproj/project.pbxproj
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Network/Service/WebtoonService.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Home/Cell/AllToonsSectionCell.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Home/Cell/ToonCategorySectionCell.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Home/Model/AllToonsSectionApp.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Home/View/HomeView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Home/View/ToonCategoryHeaderView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Home/ViewController/HomeViewController.swift
Labels: 🧤Network, 현수🍉, ☃️Feat

#60 [Feat] #59 - 홈뷰 웹툰 count
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Home/View/AllToonsSectionHeaderView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Home/ViewController/HomeViewController.swift
Labels: 현수🍉, ☃️Feat

#61 [Chore] #54 - HomeView 대표웹툰Section UI 수정
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Home/Cell/adSectionCell.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Home/View/AllToonsSectionFooterView.swift
Labels: 현수🍉, 🪐Chore, 🎨Style

#64 [Feat] #41 - EpisodeViewController UI 구현
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS.xcodeproj/project.pbxproj
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Application/SceneDelegate.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Extension/UIBarButtonItem+.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Resources/Assets.xcassets/AppImage/episode/ic_ arrow_left 1.imageset/Contents.json
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Resources/Assets.xcassets/AppImage/episode/ic_ arrow_left 1.imageset/ic_ arrow_left.svg
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Resources/Assets.xcassets/AppImage/episode/img_episode_ex.imageset/Contents.json
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Resources/Assets.xcassets/AppImage/episode/img_episode_ex.imageset/img_episode_ex.svg
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Episode/Cell/EpisodeCell 2.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Episode/Cell/EpisodeCell.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Episode/Cell/EpisodeHeaderCell.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Episode/View/EpisodeCellHeaderView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Episode/View/EpisodeDetailHeaderView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Episode/View/EpisodeHeaderView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Episode/View/EpisodeTabBarView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Episode/ViewController/EpisodeViewController.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Home/ViewController/HomeViewController.swift
Labels: ☃️Feat, 지원🍒, 🎨Style

#63 [Feat] #62 - 홈뷰 추가 구현
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Resources/Assets.xcassets/AppImage/main/img_tooncard_blank.imageset/Contents.json
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Global/Resources/Assets.xcassets/AppImage/main/img_tooncard_blank.imageset/img_tooncard_blank2.svg
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Home/Cell/AllToonsSectionCell.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Home/View/AllToonsSectionFooterView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Home/View/HomeView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Home/View/ToonCategoryHeaderView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Home/ViewController/HomeViewController.swift
Labels: 💨Fix, ☃️Feat, 승원🍋

#66 [Network] #65 - api 연결 완료
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Application/SceneDelegate.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Network/Base/EpisodeTargetType.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Network/Service/EpisodeService.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Episode/Cell/EpisodeCell.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Episode/View/EpisodeHeaderView.swift
  KAKAOWEBTOON-iOS/KAKAOWEBTOON-iOS/Presentation/Episode/ViewController/EpisodeViewController.swift
Labels: 🧤Network, 지원🍒
